# Generated by Django 5.0.6 on 2024-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pessoa', models.CharField(max_length=30)),
                ('assistido', models.BooleanField()),
            ],
        ),
    ]
