# Generated by Django 4.2.13 on 2024-05-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='assistido',
            field=models.BooleanField(null=True),
        ),
    ]
