version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: api-movies
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
        
volumes:
  postgres_data:
